### ISSUE TITLE
Error in x[["Version"]] : subscript out of bounds

### ISSUE THREAD

**Issue by daniswan** [biodavidjm/artMS#100]
Updated artMS to most recent version on github.  Re-ran analysis that had worked minutes before without error and got this:

>> RUNNING MSstats
-- Normalization method: equalizeMedians
Error in x[["Version"]] : subscript out of bounds

Note, I downloaded the newset version because I noticed that for enrichment analysis only the CORUM results were being plotted, not any of the gProfiler results, so wanted to see if that was a bug that had been fixed in newer version.

**Comment by biodavidjm** [comment]
I cannot reproduce the error, therefore more information is needed. Does the preliminary step work well? 

`-- Write out the MSstats input file (-mss.txt)`

Please, check the `-mss.txt` file and see if it's fine.

With respect to the enrichment using `gProfiler`, it is an [online service](https://biit.cs.ut.ee/gprofiler/gost), so if the server is down, `artMS` skips the enrichment analysis
