### ISSUE TITLE
artmsProtein2SiteConversion {artMS} error in everything

### ISSUE THREAD

**Issue by daniswan** [biodavidjm/artMS#103]
artmsProtein2SiteConversion("evidence.txt", "SwissProtReviewed_mouse_20180904.fasta",
                            column_name = c("Leading razor protein"), "ph-sites-evidence.txt", "PH", overwrite_evidence = FALSE,
                            verbose = TRUE)

Got the following error:  
--- ALL SEQUENCES MAPPED 
Error in everything() : could not find function "everything"

No output file was written.
MQ Version 1.6.3.3

**Comment by biodavidjm** [comment]
The problem will be fixed soon but it will require updating R and bioconductor (if you haven't already). In the meantime, just load the library `dplyr` and should solve the problem:

```
library(dplyr)
library(artMS)

artmsProtein2SiteConversion(evidence_file = "evidence.txt", 
                            ref_proteome_file = "SwissProtReviewed_mouse_20180904.fasta",
                            column_name = "Leading razor protein", 
                            output_file = "ph-sites-evidence.txt", 
                            mod_type = "PH", 
                            overwrite_evidence = FALSE)
```
