### ISSUE TITLE
Silac type of analysis  'breaks' are not unique error

### ISSUE THREAD

**Issue by algom** [biodavidjm/artMS#110]
Hello,

I'm testing out artMS on my analysis, however I haven't been able to run it. I always get the following error after starting it:

`artmsQualityControlEvidenceBasic("evidence.txt", keys_file = "keys.txt")`

```
artMS: BASIC QUALITY CONTROL (-evidence.txt based).

---------------------------------------------
>> MERGING FILES 
-- Plot: intensity distribution
-- Plot: Reproducibility scatter plots
|=========================================================================================| 100%
-- Plot: correlation matrices
---- NO Technical Replicates detected 
---- by Biological replicates 
---- by Conditions 
Error in cut.default(x, breaks = breaks, include.lowest = T) : 
  'breaks' are not unique
```
I do isotopic labeling with formaldehyde (similar to SILAC but chemical) so the data structure should be the same. I have looked to see if there is a "sample" SILAC dataset in the package but I haven't found one.

The error might be in my keys file or contrast file? As a start (later I will add more complexity) I have 4 biological replicates, i.e 4 runs;

Raw file names: TF01.raw, TF02.raw, TF03.raw, TF04.raw

My Keys.txt file:
Raw.file | IsotopeLabelType | Condition | BioReplicate | Run
TF01 | H | wt | wt-1 | 1
TF02 | H | wt | wt-2 | 2
TF03 | H | wt | wt-3 | 3
TF04 | H | wt | wt-4 | 4
TF01 | L | wt_ko | wt_ko-1 | 1
TF02 | L | wt_ko | wt_ko-2 | 2
TF03 | L | wt_ko | wt_ko-3 | 3
TF04 | L | wt_ko | wt_ko-4 | 4

Contrast.txt:
wt-wt_ko

And in the .yaml file I pointed to the path with the 3 files, and has a "1" to enable the SILAC in that section.

Does it matter how the "Experiment" was called in MaxQuant?, in my setup was exp1, exp2, exp3, exp4, for that example.

If I disable all plots in the yaml file it goes a little bit further but then gives this error:
```
artmsQuantification(yaml_config_file = "config2.yaml")
```
```
--------------------------------------------
artMS: Relative Quantification using MSstats
--------------------------------------------
>> READING THE CONFIGURATION FILE
-- No QC basic selected
-- No evidence-extended QC selected
-- No summary-based QC selected
>> QUANTIFICATION: LOADING DATA 
>> PROCESSING SILAC EVIDENCE FILE 
--- File /home/laptop/Documents/MQ_ko/May/evidence-silac.txt is ready 
Error in .artms_writeContrast(contrast_file = config$files$contrasts,  : 
  These conditions are not found in the dataset: wt,wt_ko
```

Any help would be appreciated.

**Comment by biodavidjm** [comment]
Hi there,

I don't see anything wrong with the keys file. I think the problem is with the Quality Control functions, that have basically evolved to handle label-free data and not SILAC data (and a lack of a test for silac data has not complained ;-)

To test my preliminary hypothesis, would you mind to turn off the quality control options in the configuration file, i.e:

```
qc:
  basic: 0
  extended: 0
  extendedSummary: 0
```

Please, let me know how it goes. Thanks

**Comment by algom** [comment]
Hello,

I tried it but no luck:
```
artmsQuantification(yaml_config_file = "config2.yaml")
```
```
--------------------------------------------
artMS: Relative Quantification using MSstats
--------------------------------------------
>> READING THE CONFIGURATION FILE
-- No QC basic selected
-- No evidence-extended QC selected
-- No summary-based QC selected
>> QUANTIFICATION: LOADING DATA 
>> PROCESSING SILAC EVIDENCE FILE 
--- File /home/laptop/Documents/MQ_ko/May/evidence-silac.txt is ready 
>> MERGING FILES 
--(-) Raw.files in keys not found in evidence file: TF01H	TF01L	TF02H	TF02L	TF03H	TF03L	TF04H	TF04L
--(-) Raw.files in evidence not found in keys file: H	L
Error: argument is not interpretable as logical
```
I tried doing each function at a time, but as the error indicates I guess is in the merging of the keys with the evidence data frame 

Thanks

**Comment by biodavidjm** [comment]
Thanks! that test is enough to know what's going on. Let me work on fixing it.

**Comment by biodavidjm** [comment]
Hi @algom 

Sorry for the delay, I had to address more issues than I expected. But please, check the new artMS version available at bioconductor (1.2.3) or directly install it from github. And please, let me know how it goes.

**Comment by algom** [comment]
Hello,

Sorry also for the late reply. So, far I have tried it and its working! I'm now testing more thoroughly and including fractions as my experiments mainly include fractionation. 

Thanks!

**Comment by biodavidjm** [comment]
Great! let us know if anything goes wrong.
