### ISSUE TITLE
Analysis of quantification error:  "Aggregation function missing: defaulting to length"

### ISSUE THREAD

**Issue by daniswan** [biodavidjm/artMS#117]
This is for a DIA experiment.  Data was exported from Spectronaut in MSstats format.  artMSQuantification ran successfully, but generated an error on artmsAnalysisQuantifications step.

## Code executed

library(artMS)
artmsQuantification("config.yaml", verbose=TRUE)
artmsAnalysisQuantifications("results.txt", "results_ModelQC.txt", "MOUSE",
                             output_dir = "CK5", enrich = TRUE, l2fc_thres = 1.0,
                             choosePvalue = c("adjpvalue"),
                             isBackground = "nobackground", isPtm = "global", mnbr = 3,
                             isFluomics = FALSE, pathogen = "nopathogen",
                             plotPvaluesLog2fcDist = TRUE, plotAbundanceStats = TRUE,
                             plotReproAbundance = TRUE, plotCorrConditions = TRUE,
                             plotCorrQuant = TRUE, plotPCAabundance = TRUE,
                             plotFinalDistributions = TRUE, plotPropImputation = TRUE,
                             plotHeatmapsChanges = TRUE, plotTotalQuant = TRUE,
                             plotClusteringAnalysis = TRUE, verbose = TRUE)

## error message

```
> artmsAnalysisQuantifications("results.txt", "results_ModelQC.txt", "MOUSE",
+                              output_dir = "CK5", enrich = TRUE, l2fc_thres = 1.0,
+                              choosePvalue = c("adjpvalue"),
+                              isBackground = "nobackground", isPtm = "global", mnbr = 3,
+                              isFluomics = FALSE, pathogen = "nopathogen",
+                              plotPvaluesLog2fcDist = TRUE, plotAbundanceStats = TRUE,
+                              plotReproAbundance = TRUE, plotCorrConditions = TRUE,
+                              plotCorrQuant = TRUE, plotPCAabundance = TRUE,
+                              plotFinalDistributions = TRUE, plotPropImputation = TRUE,
+                              plotHeatmapsChanges = TRUE, plotTotalQuant = TRUE,
+                              plotClusteringAnalysis = TRUE, verbose = TRUE)
---------------------------------------------
artMS: ANALYSIS OF QUANTIFICATIONS
---------------------------------------------
--- No Pathogen extra in these samples
>> LOADING modelqc FILE (ABUNDANCE) 
--- Total number of genes/proteins: 5169 
>> LOADING QUANTIFICATIONS (-results.txt from MSstats) 
>> IMPUTING MISSING VALUES 
--- Number of +/- INF values: 2030 
Aggregation function missing: defaulting to length
Error in vapply(indices, fun, .default) : values must be length 272297,
 but FUN(X[[1]]) result is length 1
```

**Comment by biodavidjm** [comment]
The problem is that the biological replicates names don't follow the artMS naming rules, i.e., Condition_name-Biological_replicate_number
