### ISSUE TITLE
Error reported when converting the data to MSStats format

### ISSUE THREAD

**Issue by weixiandeng** [biodavidjm/artMS#135]
While processing some data, it reported following error and processing aborted:

>> CONVERTING THE DATA TO MSSTATS FORMAT 
-- Selecting Sequence Type: MaxQuant 'Modified.sequence' column
-- Adding NA values for missing values (required by MSstats) 
-- Write out the MSstats input file (-mss.txt) 
Error in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection

Warning messages:
1: In read.table(file = file, header = header, sep = sep,  ... :
  incomplete final line found by readTableHeader on '../keys.txt'
2: In data.table::dcast(data = b, Feature + Proteins ~ BioReplicate,  ... :
  The dcast generic in data.table has been passed a data.frame and will attempt to redirect to the reshape2::dcast; please note that reshape2 is deprecated, and this redirection is now deprecated as well. Please do this redirection yourself like reshape2::dcast(b). In the next version, this warning will become an error.
3: Removed 9905 rows containing non-finite values (stat_density2d).
4: Removed 9905 rows containing non-finite values (stat_smooth).
5: In data.table::dcast(data = b, Feature + Proteins ~ BioReplicate,  ... :
  The dcast generic in data.table has been passed a data.frame and will attempt to redirect to the reshape2::dcast; please note that reshape2 is deprecated, and this redirection is now deprecated as well. Please do this redirection yourself like reshape2::dcast(b). In the next version, this warning will become an error.
6: Removed 8798 rows containing non-finite values (stat_density2d).
7: Removed 8798 rows containing non-finite values (stat_smooth).
8: In data.table::dcast(data = biorepliaggregated, Proteins +  ... :
  The dcast generic in data.table has been passed a data.frame and will attempt to redirect to the reshape2::dcast; please note that reshape2 is deprecated, and this redirection is now deprecated as well. Please do this redirection yourself like reshape2::dcast(biorepliaggregated). In the next version, this warning will become an error.
9: In data.table::dcast(data = biorepliaggregated, Proteins +  ... :
  The dcast generic in data.table has been passed a data.frame and will attempt to redirect to the reshape2::dcast; please note that reshape2 is deprecated, and this redirection is now deprecated as well. Please do this redirection yourself like reshape2::dcast(biorepliaggregated). In the next version, this warning will become an error.
10: In read.table(file = file, header = header, sep = sep,  ... :
  incomplete final line found by readTableHeader on '../keys.txt'
11: In read.table(file = file, header = header, sep = sep,  ... :
  incomplete final line found by readTableHeader on '../keys.txt'
12: In file(file, ifelse(append, "a", "w")) :
  cannot open file '..-mss.txt/evidence-mss.txt': No such file or directory

Not in all different datasets, in some but not all.

Thanks!

Weixian

**Comment by biodavidjm** [comment]
Hi @weixiandeng 

It looks like something is wrong with your keys.txt file. In order to debug the issue properly, would you mind to provide the artMS function that you run? Assuming that it was `artmsQuantification()`, would you mind to copy and paste the `configuration.yaml` file?
Thanks!

**Comment by weixiandeng** [comment]
Thank you for your response.
Yeah you are right, it's from 
artmsQuantification(yaml_config_file = 'config.yaml')
function.

Please see below: 
[keys.txt](https://github.com/biodavidjm/artMS/files/4041668/keys.txt)

Content of my Yaml file
files:
  evidence: ../txt/evidence.txt
  keys: ../keys.txt
  contrasts: ../contrast.txt
  summary: summary.txt
  output: ../results.txt
qc:
  basic: 1
  extended: 0
  extendedSummary: 0
data:
  enabled: 1
  fractions:
    enabled: 0
  silac:
    enabled: 0
  filters:
    enabled: 1
    contaminants: 1
    protein_groups: keep
    modifications: AB
  sample_plots: 0
msstats:
  enabled: 1
  msstats_input: ~
  profilePlots: none
  normalization_method: equalizeMedians
  normalization_reference: ~
  summaryMethod: TMP
  censoredInt: NA
  cutoffCensored: minFeature
  MBimpute: 1
  feature_subset: all
output_extras:
  enabled: 0
  annotate:
    enabled: 0
    species: HUMAN
  plots:
    volcano: 1
    heatmap: 0
    LFC: -1.5 1.5
    FDR: 0.05
    heatmap_cluster_cols: 0
    heatmap_display: log2FC

**Comment by biodavidjm** [comment]
Thanks. What's your operating system? I guess it is a Mac or Linux, isn't it?

If so, then I think it will solve the problem if you provide the full path for the files. You could either:

```
files:
  evidence: /Users/weixiandeng/path/to/the/evidence.txt
  keys: /Users/weixiandeng/path/to/the/keys.txt
  contrasts: /Users/weixiandeng/path/to/the/contrast.txt
  summary: /Users/weixiandeng/path/to/the/summary.txt
  output: /Users/weixiandeng/path/to/the/output/results/results.txt
```

or 

```
files:
  evidence: ~/path/to/the/evidence.txt
  keys: ~/path/to/the/keys.txt
  contrasts: ~/path/to/the/contrast.txt
  summary: ~/path/to/the/summary.txt
  output: ~/path/to/the/output/results/results.txt
```
i.e., use `~` if you don't want to write the user's home (i.e. in the example above, `/Users/weixiandeng/`).

**Important**: if you decide to output the results to a "results" folder (I recommend it), please, make sure that the folder exists (`artMS` does not create the folder, only the files, in this case).

Please, give it a try and let me know.
