### ISSUE TITLE
Error in .artms_checkRawFileColumnName(x)

### ISSUE THREAD

**Issue by gurpreet-bioinfo** [biodavidjm/artMS#136]
Hi there,

I generated **keys.txt** file as per the [requirements](https://bioconductor.org/packages/release/bioc/vignettes/artMS/inst/doc/artMS_vignette.html#inputfiles), which can be read by `read.delim` leading to data frame.

However, while running `artmsQualityControlEvidenceBasic` , I am getting following error:
```
Error in .artms_checkRawFileColumnName(x) : 
  cannot find the <Raw.file> column
```

Also, gets the same error while providing path of the file in the above command.

Thanks.
Gurpreet

**Comment by biodavidjm** [comment]
HI @gurpreet-bioinfo 

please, make sure that the name of the column with the raw files is exactly `RawFile`. Same thing with all the other required columns: they must be named as indicated in the guidelines, i.e., 


`RawFile | IsotopeLabelType | Condition | BioReplicate | Run`

Please, let me know how it goes (if it fails, please, provide the output of the command 
`colnames( keys_data_frame)`

**Comment by gurpreet-bioinfo** [comment]
Hi @biodavidjm ,

Here is the output:

```
>colnames(keys_file)
[1] "RawFile"          "IsotopeLabelType" "Condition"        "BioReplicate"     "Run"             

>str(keys_file)
'data.frame':	13 obs. of  5 variables:
 $ RawFile         : chr  "Q1" "Q2" "Q3" "Q4" ...
 $ IsotopeLabelType: chr  "L" "L" "L" "L" ...
 $ Condition       : chr  "Control" "Control" "Control" "Control" ...
 $ BioReplicate    : chr  "Control-1" "Control-2" "Control-3" "Control-4" ...
 $ Run             : int  1 1 1 1 1 1 1 2 2 2 ...
```

**Comment by biodavidjm** [comment]
The `RawFile` column is correct. 
`keys.txt` seems correct, except for the `Run` column, that if you have 13 samples, it should go from 1 to 13.

If the keys file is correct, then it should be the evidence file the one with the "problem". Have you checked the evidence file and make sure it has a "Raw file" column?

If it does not work, could you please paste here the entire output when running the artms command?

Please, let me know how it goes

**Comment by gurpreet-bioinfo** [comment]
Thanks @biodavidjm !

I have MaxQuant proteinGroups.txt as my input. Indeed "Raw file" column is missing.

**Comment by gurpreet-bioinfo** [comment]
@biodavidjm I could not find the way to read `proteinGroups.txt` into artMS from https://bioconductor.org/packages/release/bioc/vignettes/artMS/inst/doc/artMS_vignette.html but 
https://www.bioconductor.org/packages/devel/bioc/manuals/artMS/man/artMS.pdf indicates 
the use of `prot_group_file` . I don't have MaxQuant searched data (evidence) file but proteinGroups.txt. 

As per artms_data_ph_evidence).RData, RawFile is a separate column. I a

Is there a way to use `artmsMsstatsSummary` with proteinGroups.txt?

Thanks.

**Comment by biodavidjm** [comment]
Unfortunately, `artmsMsstatsSummary` only works providing both the `evidence.txt` and `proteinGroups.txt` files.

Currently, the analysis of proteinGroups file alone is not currently supported.

**Comment by gurpreet-bioinfo** [comment]
Ok @biodavidjm . I hope it will be possible in future releases. :-)
