### ISSUE TITLE
Error in Protein ID overlap matrix from QC-ID-Overlap.pdf

### ISSUE THREAD

**Issue by JoshEbner** [biodavidjm/artMS#141]
<img width="527" alt="Screenshot 2020-02-10 at 14 03 46" src="https://user-images.githubusercontent.com/58002390/74152297-4ccd5680-4c0e-11ea-883b-1a208845abe8.png">

The matrix with ID overlaps is unreadable due to scaling issues I suppose.
Is there any way to get a readable plot?

Thank you very much and best regards,
Joshua

**Comment by biodavidjm** [comment]
Thanks for reporting this. Quick question, how many biological replicates do you have in total?

**Comment by JoshEbner** [comment]
Hi, I had 8 biological replicates per group, so 24 biological replicates in total
