### ISSUE TITLE
read.table error on evidence.txt file

### ISSUE THREAD

**Issue by Deanho** [biodavidjm/artMS#162]
Hi, I got he following error when testing artMS on my data, starting with the most basic analysis:

artmsQualityControlEvidenceBasic("arguments"):

Gives:
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  more columns than column names

It seems it's failing right at the start - reading the evidence.txt file.
Maybe it's an error/issue with read.table, which I don't often use. If I try:

read.table("my_evidence.txt file") it says my second line doesn't have X elements, regardless of whether I say header=T or F. 

Regards,
Dean

**Comment by biodavidjm** [comment]
Hi. This is something that seems to be related with your `evidence.txt` or the `keys.txt` file, which might not be according to the expected format (tab-delimited)

Just try:

```
evidence <- read.delim("/path/to/evidence.txt", stringsAsFactors = FALSE)
keys <- read.delim("/path/to/keys.txt", stringsAsFactors = FALSE)
```
which is all what `artMS` is doing. If any of those fails, it should help you identifying the problem with your files. Please, let me know how it goes.

**Comment by Deanho** [comment]
Hi,

Thanks for the rapid response. Yes. You were right. The headers of my keys.txt file were space, not tab, delimited.

It works now.

Cheers,

Dean

________________________________

**Comment by biodavidjm** [comment]
Glad it works now!
