### ISSUE TITLE
Issue with results-summary.xlsx (in "wide" tables, missing results get iLog2FC and iPvalue = 0)

### ISSUE THREAD

**Issue by OlgaTSchubert** [biodavidjm/artMS#175]
Hi David,

When artMS creates the "wide" format tables for the results-summary.xlsx file, it seems to fill the values of missing comparisons with "0". This is problematic because it then seems like these are highly significant rather than just completely missing. 

Would it be possible to change the values for these missing comparisons to "NA" rather than "0" - preferably for both the log2FC and the p-values?

Thank you!
Olga

**Comment by biodavidjm** [comment]
Thanks for reporting this. It will definitely be fixed

**Comment by biodavidjm** [comment]
Issue already solved. Please, update to artMS version 1.10.2 (it requires R >= 4.1.0)
