### ISSUE TITLE
Issue with results table: for pvalues that are NA, adj.pvalue is 0

### ISSUE THREAD

**Issue by OlgaTSchubert** [biodavidjm/artMS#177]
Hi David (@biodavidjm)

This is a similar issue to #175 that I reported earlier.

In the results table of artMS called results-log2fc-long.txt, the adj.pvalue is "0" for all pvalues that are "NA". I think this adj.pvalue should remain an "NA" otherwise it is misleading, right?

Thanks for looking into this!

Olga

**Comment by biodavidjm** [comment]
Absolutely. This will be fixed. I think this problem might be the consequence of having recently refactored code and used a different package to reshape the data. I guess that, by default, this package adds zeros (?). I will check and fix it. Thanks for reporting this!

**Comment by biodavidjm** [comment]
Fixed in version 1.8.4
