### ISSUE TITLE
artmsAnalysisQuantifications error

### ISSUE THREAD

**Issue by Monod79** [biodavidjm/artMS#179]
Hi ! 

I was running (under R version 4.0.4) your pipeline (really impressive !) until I got the following error while performing the relative quantification analysis. 

Here's the error :

![image](https://user-images.githubusercontent.com/52295327/116531732-7cb55800-a8ad-11eb-9bcf-e708bbce25c9.png)

Any clue ?

**Comment by biodavidjm** [comment]
Hi @Monod79,

I've noticed too many infinite values (3740) out of the total number of proteins quantified (3820). It looks like you might be comparing things that are too different. It could help to rule out that suspicion if you check the following:

- Open the `artMS - EVs Optiprep vs Secretome.txt` file. Inspect the log2FC column. What proportion of values do you have there? it looks like you might have mostly INF / -INF values
- if you run the `artmsQualityControlEvidenceExtended()` function, how does the ID overlap look like? what's the overlap between the (I assume) 2 conditions?

Please, let us know. Thanks!

**Comment by Monod79** [comment]
Hi @biodavidjm , 

Thanks for the fast answer! I was performing 4 contrasts where 2 of them were just exploratory. After removing these fishy contrasts, I'm still getting the same error, having 1229 +/- Inf values out of 3820 proteins. This is expected, as we're looking for unique and/or highly enriched proteins in one of the conditions. I've been able to run smoothly the artmsQuantification() function, which involves imputation. 

![image](https://user-images.githubusercontent.com/52295327/116652347-fe12f600-a952-11eb-9c8e-00b5173bc463.png)

What are my options? I really hope to make this work, it looks like a really promising pipeline that I would like to implement. 

Joe

**Comment by biodavidjm** [comment]
Hi @Monod79 ,

I am running out of ideas without seeing the files. Would you be willing to share the files via email or similar? I would be happy to debug the problem and, after identifying the problem, add checkpoints to provide a better error explanation. If you are willing to share the files, please, send them to artms.help@gmail.com and they will be treated confidentially.

Please, let me know.

**Comment by biodavidjm** [comment]
Issue identified: the `keys.txt` contains the bioreplicate numbers using underscore instead of dashes, which makes the analysis of quantifications fail. As specified in the [vignette, "required input files" > "keys.txt"](http://artms.org/):

>  BioReplicate: biological replicate number. It is based on the condition name. Use as prefix the corresponding Condition name, and add as suffix dash (-) plus the biological replicate number. For example, if condition H1N1_06H has too biological replicates, name them H1N1_06H-1 and H1N1_06H-2

The next version of `artMS` will include new checkpoints to validate this requirement.

**Comment by Monod79** [comment]
Many thanks David !
