### ISSUE TITLE
Error: object of type 'closure' is not subsettable

### ISSUE THREAD

**Issue by daniswan** [biodavidjm/artMS#79]
I am trying to run artMS using a pre-formatted MSstats input file and getting an error.  I have also tested using artMS to generate the evidence-mss.txt and then loading in this file and get the same error.  Here is my config file for reference:

files:
  evidence: C:/JMP3/evidence.txt
  keys: C:/JMP3/keys.txt
  contrasts: C:/JMP3/contrast.txt
  output: C:/JMP3/results_folder/results.txt
qc:
  basic: 0
  extended: 0
data:
  enabled: 0
  fractions:
    enabled: 0
  silac:
    enabled: 0
  filters:
    enabled: 1
    contaminants: 1
    protein_groups: remove
    modifications: AB
  sample_plots: 1
msstats:
  enabled: 1
  msstats_input: C:/JMP3/evidence-mss.txt
  profilePlots: none
  normalization_method: equalizeMedians
  normalization_reference: ~
  summaryMethod: TMP
  censoredInt: NA
  cutoffCensored: minFeature
  MBimpute: 1
  feature_subset: all
output_extras:
  enabled: 1
  annotate:
    enabled: 1
    species: HUMAN
  plots:
    volcano: 1
    heatmap: 1
    LFC: -1 1
    FDR: 0.05
    heatmap_cluster_cols: 0
    heatmap_display: log2FC

**Comment by biodavidjm** [comment]
HI @daniswan 
Thanks for reporting this problem. It has been now fixed. artMS version 1.0.3 should be available soon at bioconductor with the latest fixed version.
Thanks!
