### ISSUE TITLE
SaintExpress spectral count formatted file

### ISSUE THREAD

**Issue by daniswan** [biodavidjm/artMS#90]
artMS is looking for column labeled "MS/MS Count",  but current versions of MaxQuant have that column labeled as "MS/MS count".  artMS gives error:

Error in setnames(data_f, "MS/MS Count", "spectral_counts") : 
  Items of 'old' not found in column names: MS/MS Count

**Comment by biodavidjm** [comment]
Fixed. Please, give it a try.
